name: "Hello <name>"

# description: "Release Package workflow to install dependencies, run tests, and check code quality."
description: A simple packaged action to print Hello, <name>
inputs:
  greet_name:
    description: "Name of the person to greet"
    required: true
    default: "World"

runs:
  using: "composite"
  steps:
    # - name: Check out code
    #   uses: actions/checkout@v3
      
    # - name: ls
    #   shell: bash
    #   run: ls -Rl

    - name: Run hello.py
      shell: bash
      run: python .github/actions/release-package/hello.py ${{ inputs.greet_name }}
