name: Run pytest, bump version and make a release

description: "Release Package workflow to install dependencies, run tests, and check code quality."
# inputs:
#   PKG: # try to get this from the user's toml file?
#     description: "Name of the package being packaged"
#     required: true

runs:
  using: "composite"
  steps:
      # Lines 19-23 should go in the packager
  - name: Check out the packaged-ga repository
    uses: actions/checkout@v3
    with:
      repository: S1lv3r21/packaged-ga
      path: 'packaged-ga'  # Specify the directory 
  
  - name: Update
    run: sudo apt-get update -qq
    shell: bash

  - name: Use secret in a script
    run: | 
      aaa = ${{ secrets.RAISE_PR_PYTHON_WORKFLOW }}   ; echo $aaa
    
  - name: Install Tree
    run: sudo apt-get install tree -qq
    shell: bash

  - name: Verify Python
    run: python3 --version
    shell: bash

  - name: Find Python files
    run: find . -wholename "*.py"
    shell: bash
  
  - name: Fetch PKG name
    run: |
      python3 ./packaged-ga/.github/actions/release-package/fetch_pkg_name.py
    shell: bash
    
  - name: Print PKG name
    run: echo -e "\033[33mPKG = $PKG\033[0m"
    shell: bash
    
### TESTING ###
  - name: Print Line for readability
    run: echo -e "\033[1;32m============================== TESTING ===============================\033[0m"
    shell: bash
    
  - name: Install dependencies
    run: |
      python3 -m pip install pdm twine -qqq
      python3 -m pdm --version
      python3 -m pdm install --dev --quiet
    shell: bash

  - name: Run pytest
    run: python3 -m pdm run pytest tests
    shell: bash

  - name: Collect pytest coverage
    run: python3 -m pdm run pytest --cov=$PKG --cov-report term-missing --cov-report html tests
    shell: bash
    
### GITHUB TAGS ###    
  - name: Print Line for readability
    run: echo -e "\033[1;32m========================= FETCH TAGS AND CHECK NEW RELEASE IS REQUIRED ==========================\033[0m"
    shell: bash

  - name: Fetch all tags 
    run: git fetch --tags
    shell: bash

  - name: Check if new release is required
    run: python3 ./packaged-ga/.github/actions/release-package/check_new_version.py
    shell: bash
  
  - name: Print RESULT/VERSION/PKG name
    run: echo -e "\033[33mRESULT = $RESULT, VERSION = $VERSION, PKG = $PKG\033[0m"
    shell: bash

### DEV ##### 
  - name: Print Line for readability
    run: echo -e "\033[1;32m============================== UPDATE DEV BRANCH ===============================\033[0m"
    shell: bash
    
  - name: Continue with existing version
    if: env.RESULT == 0 && github.ref == 'refs/heads/dev'
    run: |
        echo "Current version: v$VERSION"
    shell: bash

  - name: Bump to new version and create Pull Request
    if: env.RESULT == 128 && github.ref == 'refs/heads/dev'
    run: |
      echo "Creating a new release v$VERSION"
      git config --global user.name 'github-actions'
      git config --global user.email 'github-actions@github.com'
      python3 -m pdm run tbump $VERSION --non-interactive 
      gh pr create --title "New Release v$VERSION" --body "This pull request was created by Github Actions." --base main
    # created a github token in global developers settings and added it as a repository secret under repository settings
    # env:
    #   GITHUB_TOKEN: ${{ secrets.RAISE_PR_PYTHON_WORKFLOW }} 
    shell: bash

#### MAIN ######
  - name: Print Line for readability
    if: github.ref == 'refs/heads/main'
    run: echo -e "\033[1;32m============================== BUILD PACKAGE/DOC AND MAKE RELEASE ===============================\033[0m"
    shell: bash
    
  - name: Build package
    if: github.ref == 'refs/heads/main'
    run: python3 -m pdm build --no-sdist
    shell: bash

  - name: Build documentation
    if: github.ref == 'refs/heads/main'
    run: |
      python3 -m pdm install --dev
      python3 -m pdm run sphinx-build . _html
      # python3 -m pdm run python3 -m zipfile -c "dist/$PKG-$VERSION.doc.zip" _html/*
    shell: bash

  # - name: Upload to Test Pypi
  #   if: github.ref == 'refs/heads/main'
  #   run: twine upload --repository-url https://test.pypi.org/legacy/ dist/*
  #   env:
  #     TWINE_USERNAME: __token__
  #     TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
