name: Print Hello <name>

on:
  push:
    branches: [ main ]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Greet <name>
      uses: S1lv3r21/packaged-ga/@main
      with:
        greet_name: "Every-one"
